import { Dancing_Script } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Navigation from "./components/navbar";

const scriptFont = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-script",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className={`${scriptFont.variable}`}>
      <body className="antialiased font-[var(--font-body)]">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
