import { DM_Serif_Display, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Navigation from "./components/navbar";

const headingFont = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-heading",
});

const bodyFont = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-body",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${headingFont.variable} ${bodyFont.variable}`}>
      <body className="antialiased font-[var(--font-body)]">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
